const catalog = {
 Melee:['Attack','Punish','Dismember','Slice','Havoc','Backhand','Barge','Greater Barge','Fury','Greater Fury','Flurry','Greater Flurry','Sever','Smash','Cleave','Decimate','Hurricane','Quake','Forceful Backhand','Slaughter','Assault','Destroy','Blood Tendrils','Massacre','Meteor Strike','Frenzy','Berserk','Balanced Strike','Chaos Roar','Overpower','Igneous Overpower','Rend','Adaptive Strike'],
 Ranged:['Ranged','Piercing Shot','Snipe','Greater Snipe','Fragmentation Shot','Dazing Shot','Greater Dazing Shot','Needle Strike','Binding Shot','Demoralise','Ricochet','Greater Ricochet','Corruption Shot','Snap Shot','Rapid Fire','Bombardment','Tight Bindings','Shadow Tendrils','Deadshot','Incendiary Shot','Death’s Swiftness','Unload'],
 Magic:['Magic','Wrack','Wrack and Ruin','Sonic Wave','Greater Sonic Wave','Concentrated Blast','Greater Concentrated Blast','Dragon Breath','Combust','Impact','Chain','Greater Chain','Corruption Blast','Asphyxiate','Wild Magic','Horror','Smoke Tendrils','Detonate','Omnipower','Igneous Omnipower','Metamorphosis','Sunshine','Greater Sunshine','Tsunami'],
 Necromancy:['Necromancy','Conjure Skeleton Warrior','Conjure Putrid Zombie','Conjure Vengeful Ghost','Conjure Phantom Guardian','Command Skeleton Warrior','Command Putrid Zombie','Command Vengeful Ghost','Command Phantom Guardian','Touch of Death','Soul Sap','Volley of Souls','Finger of Death','Death Skulls','Living Death','Bloat','Soul Strike','Spectral Scythe','Blood Siphon','Threads of Fate','Split Soul','Invoke Death'],
 Defence:['Anticipation','Freedom','Resonance','Divert','Preparation','Reflect','Debilitate','Revenge','Bash','Provoke','Barricade','Immortality','Rejuvenate','Natural Instinct','Cease','Devotion'],
 Constitution:['Eat Food','Demon Slayer','Dragon Slayer','Undead Slayer','Tuska’s Wrath','Sacrifice','Transfigure','Guthix’s Blessing','Ice Asylum','Onslaught','Weapon Special Attack','Regenerate','Incite'],
 Utility:['Surge','Double Surge','Escape','Double Escape','Dive','Bladed Dive','Ingenuity of the Humans','Limitless','Aggression'],
 Specials:['EZK Special','Leng Special','Dragon Claws','Dragon Dagger','Dragon Longsword','Dragon Mace','Dragon 2h Sword','Statius’s Warhammer','Zaros Godsword','Armadyl Godsword','Saradomin Godsword','Guthix Godsword','Dark Bow','Seren Godbow','Bow of the Last Guardian','Eldritch Crossbow','Fractured Staff of Armadyl','Omni Guard','Devourer’s Guard']
};
const slug=s=>s.toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const iconUrl=name=>`https://runescape.wiki/images/${encodeURIComponent(name.replaceAll(' ','_'))}.png`;
let items=[]; Object.entries(catalog).forEach(([cat,names])=>names.forEach(name=>items.push({id:slug(name),name,cat,icon:iconUrl(name)})));
const A=Object.fromEntries(items.map(x=>[x.id,x]));
let rotation=[{type:'text',text:'SETUP'},slug('Meteor Strike'),slug('Adaptive Strike'),slug('Berserk'),{type:'pause',ticks:8},slug('Greater Barge'),{type:'text',text:'ZERK / EZK'},slug('Igneous Overpower'),slug('EZK Special'),slug('Greater Flurry'),slug('Rend'),slug('Hurricane'),slug('Assault')];
const $=id=>document.getElementById(id); let dragIndex=null;
function norm(x){if(typeof x==='string')return {type:'ability',id:x}; return x.type?x:{type:'text',text:x.text||'NOTE'}}
function pauseLabel(t){return `${t}t · ${(t*0.6).toFixed(1)}s`}
function tileAbility(a){let t=document.createElement('div');t.className='tile';let img=document.createElement('img');img.className='iconimg';img.src=a.icon;img.alt=a.name;img.title=a.name;img.onerror=()=>{img.style.display='none';t.querySelector('.fallback').style.display='flex'};t.appendChild(img);let f=document.createElement('div');f.className='fallback';f.textContent=a.name.split(' ').map(w=>w[0]).join('').slice(0,4);t.appendChild(f);if($('showNames').checked){let n=document.createElement('div');n.className='name';n.textContent=a.name;t.appendChild(n)}return t}
function render(){document.documentElement.style.setProperty('--icon',$('iconSize').value+'px');$('board').style.setProperty('--cols',$('perRow').value);$('board').innerHTML='';$('rotationList').innerHTML='';rotation.forEach((raw,i)=>{let x=norm(raw);let el;if(x.type==='text'){el=document.createElement('div');el.className='section';el.textContent=x.text}else if(x.type==='pause'){el=document.createElement('div');el.className='pauseTile';el.innerHTML=`<div class="pauseIcon">Ⅱ</div><b>${pauseLabel(+x.ticks||1)}</b>`}else el=tileAbility(A[x.id]||{name:x.id,icon:''});$('board').appendChild(el);
 let c=document.createElement('div');c.className='card';c.draggable=true;c.dataset.i=i;let label=x.type==='text'?`TXT · ${x.text}`:x.type==='pause'?`Ⅱ Pause · ${pauseLabel(+x.ticks||1)}`:`${(A[x.id]||{}).cat||''} · ${(A[x.id]||{}).name||x.id}`;c.textContent=label;c.ondblclick=()=>{rotation.splice(i,1);render()};c.ondragstart=()=>dragIndex=i;c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();let to=+c.dataset.i;if(dragIndex===null||to===dragIndex)return;let[m]=rotation.splice(dragIndex,1);rotation.splice(to,0,m);dragIndex=null;render()};$('rotationList').appendChild(c)});saveCurrent()}
function saveCurrent(){localStorage.setItem('rs3rot-current-v2',JSON.stringify(rotation));localStorage.setItem('rs3rot-settings-v2',JSON.stringify({icon:$('iconSize').value,cols:$('perRow').value,names:$('showNames').checked}))}
function presets(){return JSON.parse(localStorage.getItem('rs3rot-presets-v2')||'{}')} function refreshPresets(){let p=presets();$('presets').innerHTML=Object.keys(p).map(k=>`<option>${k}</option>`).join('')}
function fillPicker(){let q=$('search').value.toLowerCase(),cat=$('category').value;$('picker').innerHTML='';items.filter(a=>(cat==='All'||a.cat===cat)&&a.name.toLowerCase().includes(q)).forEach(a=>{let b=document.createElement('button');b.className='pick';b.title=a.name;b.innerHTML=`<img src="${a.icon}" onerror="this.style.visibility='hidden'"><span>${a.name}</span>`;b.onclick=()=>{rotation.push(a.id);render()};$('picker').appendChild(b)})}
['All',...Object.keys(catalog)].forEach(c=>{let o=document.createElement('option');o.textContent=o.value=c;$('category').appendChild(o)});$('category').onchange=fillPicker;$('search').oninput=fillPicker;
$('addPause').onclick=()=>{let ticks=Math.max(1,+$('pauseTicks').value||1);rotation.push({type:'pause',ticks});render()};$('addText').onclick=()=>{if($('customText').value.trim()){rotation.push({type:'text',text:$('customText').value.trim()});$('customText').value='';render()}};
['iconSize','perRow','showNames'].forEach(id=>$(id).oninput=render);$('toggleEdit').onclick=()=>{let e=$('editor'),hide=e.style.display!=='none';e.style.display=hide?'none':'block';$('toggleEdit').textContent=hide?'Show editor':'Hide editor'};
$('savePreset').onclick=()=>{let n=$('presetName').value.trim()||'Preset',p=presets();p[n]=rotation;localStorage.setItem('rs3rot-presets-v2',JSON.stringify(p));refreshPresets();$('presets').value=n};$('loadPreset').onclick=()=>{let p=presets(),n=$('presets').value;if(p[n]){rotation=p[n];render()}};$('deletePreset').onclick=()=>{let p=presets(),n=$('presets').value;delete p[n];localStorage.setItem('rs3rot-presets-v2',JSON.stringify(p));refreshPresets()};
try{let r=JSON.parse(localStorage.getItem('rs3rot-current-v2'));if(Array.isArray(r)&&r.length)rotation=r;let s=JSON.parse(localStorage.getItem('rs3rot-settings-v2'));if(s){$('iconSize').value=s.icon||46;$('perRow').value=s.cols||12;$('showNames').checked=s.names!==false}}catch(e){} refreshPresets();fillPicker();render();
